name: scaffolder
on: 
  push:
    branches: main
jobs:
  ServiceNowDevOpsChange:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: ServiceNow DevOps Change (Basic Auth)
        uses: ServiceNow/servicenow-devops-change@main
        id: change_request
        with:
          # Use username/password instead of token
          devops-integration-user-name: admin
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: https://dev208227.service-now.com
          tool-id: 35432ff783d87210340974b6feaad3bb
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNowDevOpsChange'
          change-request: '{}'
          
      - name: Show Results
        run: |
          echo "✅ Change Number: ${{ steps.change_request.outputs.change-request-number }}"
          echo "✅ Change Sys ID: ${{ steps.change_request.outputs.change-request-sys-id }}"
  deploy:
    name: 'Deploy'
    needs: ServiceNowDevOpsChange
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment scripts
        run: echo Completed Deployment
