name: scaffolder
on: 
  push:
    branches: main
jobs:
  ServiceNowDevOpsChange:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true  # Enable GitHub Actions debug logging
      ACTIONS_RUNNER_DEBUG: true  # Enable runner debug logging
    steps:
      - name: ServiceNow DevOps Change
        uses: ServiceNow/servicenow-devops-change@main
        id: change_request  # Added ID for step reference
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: https://dev208227.service-now.com
          tool-id: 35432ff783d87210340974b6feaad3bb
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow DevOps Change'
          change-request: '{"attributes":{"requested_by":{"name": "Test User"},"assignment_group":{"name": "Change Approval Team"},"priority": "2","comments": "This is a sample pipeline script to be added in your change step","work_notes": "Update this to work_notes","start_date": "2025-10-08 11:59:59","end_date": "2025-10-09 11:59:59"}}'
          deployment-gate: '{"environment": "deploy-gates-demo", "jobName": "Deploy"}'
          
      - name: Capture and echo the ServiceNow change request response
        run: |
          echo "Change Request Response: ${{ steps.change_request.outputs.change-request-number }}"
          echo "Change Request Sys ID: ${{ steps.change_request.outputs.change-request-sys-id }}"
          
          # Additional debug information
          echo "::debug::GitHub Context: ${{ toJSON(github) }}"
          echo "::debug::Job Name: ServiceNow DevOps Change"
          echo "::debug::Instance URL: https://dev208227.service-now.com"
        shell: bash
  deploy:
    name: 'Deploy'
    needs: ServiceNowDevOpsChange
    runs-on: ubuntu-latest
    environment: deploy-gates-demo
    steps:
      - name: Run deployment scripts
        run: echo Completed Deployment
 
