name: scaffolder
on: 
  push:
    branches: main
jobs:
  ServiceNowDevOpsChange:
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNowDevOpsChange
        uses: ServiceNow/servicenow-devops-change@main
        id: change_request
        with:
          #devops-integration-user-name: admin
          #devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: https://dev307459.service-now.com/
          tool-id: d90c6cae8360b210edbf9ea6feaad336
          context-github: ${{ toJSON(github) }}
          job-name: ServiceNowDevOpsChange
          change-request: '{"attributes":{"requested_by":{"name": "System Administrator"},"assignment_group":{"name": "CAB Approval"},"priority": "2","comments": "This is a sample pipeline script to be added in your change step","work_notes": "Update this to work_notes","start_date": "2025-10-14 11:59:59","end_date": "2025-10-15 11:59:59"}}'    
          #deployment-gate doesn't create a change, just finishs without
          #deployment-gate: '{"environment": "deploy-gates-demo", "jobName": "Deploy"}'
      - name: Show Results
        run: |
          echo "✅ Change Number: ${{ steps.change_request.outputs.change-request-number }}"
          echo "✅ Change Sys ID: ${{ steps.change_request.outputs.change-request-sys-id }}"
  deploy:
    name: 'Deploy'
    needs: ServiceNowDevOpsChange
    runs-on: ubuntu-latest
    #environment: deploy-gates-demo
    steps:
      - name: Run deployment scripts
        run: echo Completed Deployment
