name: scaffolder
on: 
  push:
    branches: main
jobs:
  ServiceNowDevOpsChange:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: ServiceNowDevOpsChange
        uses: ServiceNow/servicenow-devops-change@main
        id: change_request
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: https://dev208227.service-now.com
          tool-id: 35432ff783d87210340974b6feaad3bb
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow DevOps Change'
          # Use minimal change request - let ServiceNow use defaults
          change-request: '{"attributes":{"priority":"2","comments":"Automated deployment from GitHub Actions","short_description":"Deploy from GitHub workflow scaffolder"}}'
          timeout: '600'
          interval: '30'

      - name: Show Change Request Details
        run: |
          echo "Change Request Number: ${{ steps.change_request.outputs.change-request-number }}"
          echo "Change Request Sys ID: ${{ steps.change_request.outputs.change-request-sys-id }}"
  deploy:
    name: 'Deploy'
    needs: ServiceNowDevOpsChange
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment scripts
        run: echo Completed Deployment
