name: updater
on:
  schedule:
  - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: schdief/template
          upstream_branch: main
          pr_branch_name_prefix: updater
          pr_title: upstream template update
          pr_body: update from template ${SOURCE_REPO} with revision ${TEMPLATE_GIT_HASH}
          is_pr_cleanup: true
          git_remote_pull_params: --allow-unrelated-histories --squash --strategy=recursive
          steps: "prechecks,pull" 
      #place to fix merge conflicts with genai
      - uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: schdief/template
          upstream_branch: main
          pr_branch_name_prefix: updater
          pr_title: upstream template update
          pr_body: update from template ${SOURCE_REPO} with revision ${TEMPLATE_GIT_HASH}
          is_pr_cleanup: true
          git_remote_pull_params: --allow-unrelated-histories --squash --strategy=recursive
          steps: "commit,push,pr" 
