name: updater
on:
  schedule:
  - cron: "1 0 * * SUN"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: schdief/template
          upstream_branch: main
          git_remote_pull_params: --allow-unrelated-histories --strategy=recursive #by default it uses -X theirs which overrides all local changes if a file was updated on both sides, when using ours it just ignores template changes in the same situation, we need to respect both and decide intelligently
          steps: "prechecks,pull" 
      - run: git status
      #add merger to resolve merge conflicts with the help of genai
      - uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: schdief/template
          upstream_branch: main
          pr_branch_name_prefix: updater
          pr_title: upstream template update
          pr_body: update from template ${SOURCE_REPO} with revision ${TEMPLATE_GIT_HASH}
          is_pr_cleanup: true
          steps: "commit,push,pr" 
