name: updater
on:
  schedule:
  - cron: "1 0 * * SUN"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: schdief/template
          upstream_branch: main
          pr_branch_name_prefix: updater
          pr_title: upstream template update
          pr_body: update from template ${SOURCE_REPO} with revision ${TEMPLATE_GIT_HASH} /n please rescue all your own changes that are still relevant by manually editing the PR source branch
          is_pr_cleanup: true
